version: '3.2'

networks:
  pwg:
    external: false

services:
  nginx:
    networks:
      pwg:
        aliases:
          - play-with-go.dev

  gitea_prestep:
    networks:
      - pwg
    volumes:
      - $PWD/.bin/gitea:/runbin/gitea:ro

  haproxy:
    networks:
      - pwg

  pwd:
    networks:
      - pwg
    volumes:
      - $PWD/.bin/play-with-docker:/runbin/pwd:ro
    environment:
      - PWD_UNSAFE=true

  l2:
    networks:
      - pwg
    volumes:
      - $PWD/.bin/l2:/runbin/l2:ro

  site:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: ["jekyll", "serve"]

