version: '3.2'
services: 
  site:
    build:
      context: .
      dockerfile: ./docker/site/Dockerfile
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    #command: ["jekyll", "serve"]
    # Uncomment the command below to build the website
    command: ["jekyll", "build","-d", "docs", "--config", "_config.yml,_config-website.yml"]

