package ci

import (
	"tool/exec"
	"tool/file"
	"encoding/yaml"
	"strings"
)

command: gengithub: {
	root: exec.Run & {
		cmd:    "go list -m -f {{.Dir}}"
		stdout: string
	}
	#workflowsDir: "\(strings.TrimSpace(root.stdout))/.github/workflows"
	#files: {
		"\(#workflowsDir)/test.yml": test
		"\(#workflowsDir)/wip.yml":  wip
	}
	for k, v in #files {
		"\(k)": file.Create & {
			filename: k
			contents: """
		# Generated by ci_tool.cue; do not edit

		\(yaml.Marshal(v))
		"""
		}
	}
}
