package ci

import (
	"tool/exec"
	"tool/file"
	"encoding/yaml"
)

command: gengithub: {
	modRoot: exec.Run & {
		cmd:    "go list -m -f {{.Dir}}"
		stdout: string
	}
	// Loop appears to work around cuelang.org/issue/525
	for w in workflows {
		"write \(w.file)": file.Create & {
			filename: "../../.github/workflows/\(w.file)"
			contents: """
				# Generated by ci_tool.cue; do not edit

				\(yaml.Marshal(w.schema))
				"""
		}
	}
}
